pull_request_rules:
  - name: Test passed for code changed
    conditions:
      - base=master
      - "status-success=Unittest AMD64 Ubuntu 18.04"
      - "status-success=lint"
      - "status-success=Run Ci Test (standalone)"
      - "status-success=Run Ci Test (cluster)"
    actions:
      label:
        add:
          - ci-passed

  - name: Test passed for e2e changed
    conditions:
      - base=master
      - -files~=^(?!test\/).+
      - "status-success=lint"
      - "status-success=Run Ci Test (standalone)"
      - "status-success=Run Ci Test (cluster)"
    actions:
      label:
        add:
          - ci-passed
          - "test\/ci"

  - name: Test passed for document changed
    conditions:
      - base=master
      - -files~=^[^\.]+$
      - -files~=\.(?!md|png)
    actions:
      label:
        add:
          - ci-passed
          - "kind\/documentation"

  - name: Test passed for mergify changed
    conditions:
      - base=master
      - -files~=^(?!\.github\/mergify\.yml).*$
    actions:
      label:
        add:
          - ci-passed

  - name: Remove ci-passed when some test failed
    conditions:
      - base=master
      - or:
        - "check-failure=Unittest AMD64 Ubuntu 18.04"
        - "check-failure=lint"
        - "check-failure=Run Ci Test (standalone)"
        - "check-failure=Run Ci Test (cluster)"
    actions:
      label:
        remove:
          - ci-passed

  - name: Blocking PR if missing a related issue or PR doesn't have kind/improvement label
    conditions:
      - base=master
      - -body~=\#[0-9]{1,6}(\s+|$)
      - -label=kind/improvement
      - -title~=\[automated\]
    actions:
      label:
        add:
          - do-not-merge/missing-related-issue
      comment:
        message: |
          @{{author}} Please associate the related issue to the body of your Pull Request.  (eg. “issue: #187”)


  - name: Dismiss block label if related issue be added into PR
    conditions:
      - or:
        - and:
          - base=master
          - body~=\#[0-9]{1,6}(\s+|$)
        - and:
          - base=master
          - label=kind/improvement
    actions:
      label:
        remove:
          - do-not-merge/missing-related-issue

