// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-05 22:52:01.455014639 &#43;0800 CST m=&#43;0.001674288

//package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// columnBool generated columns type for Bool
type columnBool struct {
	name   string
	values []bool
}

func (c *columnBool) Name() string {
	return c.name
}

func (c *columnBool) Type() FieldType {
	return FieldTypeBool
}

func (c *columnBool) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_IntData{
				IntData: &schema.IntArray{
					Data: []int32{},
				},
			},
		},
	}
	return fd
}

func NewColumnBool(name string, values []bool) Column {
	return &columnBool {
		name: name,
		values: values,
	}
}
