// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-12 12:48:54.240744206 &#43;0800 CST m=&#43;0.002833978

//Package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// ColumnInt32 generated columns type for Int32
type ColumnInt32 struct {
	name   string
	values []int32
}

// Name returns column name
func (c *ColumnInt32) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnInt32) Type() FieldType {
	return FieldTypeInt32
}

// Len returns column values length
func (c *ColumnInt32) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnInt32) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_Int32,
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_IntData{
				IntData: &schema.IntArray{
					Data: []int32{},
				},
			},
		},
	}
	return fd
}

// NewColumnInt32 auto generated constructor
func NewColumnInt32(name string, values []int32) *ColumnInt32 {
	return &ColumnInt32 {
		name: name,
		values: values,
	}
}
