// Code generated by go generate; DO NOT EDIT
// This file is generated by go generate at 2021-07-19 17:30:03.688864552 +0800 CST m=+0.002944243

package entity 

import (
	"errors"

	"github.com/milvus-io/milvus-sdk-go/v2/internal/proto/schema"
)

// ColumnString generated columns type for String
type ColumnString struct {
	name   string
	values []string
}

// Name returns column name
func (c *ColumnString) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnString) Type() FieldType {
	return FieldTypeString
}

// Len returns column values length
func (c *ColumnString) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnString) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_String,
		FieldName: c.name,
	}
	data := make([]string, 0, c.Len())
	for i := 0 ;i < c.Len(); i++ {
		data = append(data, string(c.values[i]))
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_StringData{
				StringData: &schema.StringArray{
					Data: data,
				},
			},
		},
	}
	return fd
}

// ValueByIdx returns value of the provided index
// error occurs when index out of range
func (c *ColumnString) ValueByIdx(idx int) (string, error) {
	var r string // use default value
	if idx < 0 || idx >= c.Len() {
		return r, errors.New("index out of range")
	}
	return c.values[idx], nil
}

// Data returns column data
func (c *ColumnString) Data() []string {
	return c.values
}

// NewColumnString auto generated constructor
func NewColumnString(name string, values []string) *ColumnString {
	return &ColumnString {
		name: name,
		values: values,
	}
}
