// Code generated by go generate; DO NOT EDIT
// This file is generated by go generate at 2021-07-19 17:30:03.688864552 +0800 CST m=+0.002944243

package entity 

import (
	"errors"

	"github.com/milvus-io/milvus-sdk-go/v2/internal/proto/schema"
)

// ColumnDouble generated columns type for Double
type ColumnDouble struct {
	name   string
	values []float64
}

// Name returns column name
func (c *ColumnDouble) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnDouble) Type() FieldType {
	return FieldTypeDouble
}

// Len returns column values length
func (c *ColumnDouble) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnDouble) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_Double,
		FieldName: c.name,
	}
	data := make([]float64, 0, c.Len())
	for i := 0 ;i < c.Len(); i++ {
		data = append(data, float64(c.values[i]))
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_DoubleData{
				DoubleData: &schema.DoubleArray{
					Data: data,
				},
			},
		},
	}
	return fd
}

// ValueByIdx returns value of the provided index
// error occurs when index out of range
func (c *ColumnDouble) ValueByIdx(idx int) (float64, error) {
	var r float64 // use default value
	if idx < 0 || idx >= c.Len() {
		return r, errors.New("index out of range")
	}
	return c.values[idx], nil
}

// Data returns column data
func (c *ColumnDouble) Data() []float64 {
	return c.values
}

// NewColumnDouble auto generated constructor
func NewColumnDouble(name string, values []float64) *ColumnDouble {
	return &ColumnDouble {
		name: name,
		values: values,
	}
}
