// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-07 16:38:08.405999772 &#43;0800 CST m=&#43;0.002203053

//package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// ColumnString generated columns type for String
type ColumnString struct {
	name   string
	values []string
}

// Name returns column name
func (c *ColumnString) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnString) Type() FieldType {
	return FieldTypeString
}

// Len returns column values length
func (c *ColumnString) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnString) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_String,
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_IntData{
				IntData: &schema.IntArray{
					Data: []int32{},
				},
			},
		},
	}
	return fd
}

// NewColumnString auto generated constructor
func NewColumnString(name string, values []string) *ColumnString {
	return &ColumnString {
		name: name,
		values: values,
	}
}
