// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-12 12:48:54.240744206 &#43;0800 CST m=&#43;0.002833978

//Package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// ColumnFloat generated columns type for Float
type ColumnFloat struct {
	name   string
	values []float32
}

// Name returns column name
func (c *ColumnFloat) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnFloat) Type() FieldType {
	return FieldTypeFloat
}

// Len returns column values length
func (c *ColumnFloat) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnFloat) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_Float,
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_FloatData{
				FloatData: &schema.FloatArray{
					Data: []float32{},
				},
			},
		},
	}
	return fd
}

// NewColumnFloat auto generated constructor
func NewColumnFloat(name string, values []float32) *ColumnFloat {
	return &ColumnFloat {
		name: name,
		values: values,
	}
}
