// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-12 12:48:54.240744206 &#43;0800 CST m=&#43;0.002833978

//Package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// ColumnInt64 generated columns type for Int64
type ColumnInt64 struct {
	name   string
	values []int64
}

// Name returns column name
func (c *ColumnInt64) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnInt64) Type() FieldType {
	return FieldTypeInt64
}

// Len returns column values length
func (c *ColumnInt64) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnInt64) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_Int64,
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_LongData{
				LongData: &schema.LongArray{
					Data: []int64{},
				},
			},
		},
	}
	return fd
}

// NewColumnInt64 auto generated constructor
func NewColumnInt64(name string, values []int64) *ColumnInt64 {
	return &ColumnInt64 {
		name: name,
		values: values,
	}
}
