// Code generated by go generate; DO NOT EDIT
// This file is generated by go genrated at 2021-07-08 10:54:30.984859088 &#43;0800 CST m=&#43;0.002222031

//Package entity defines entities used in sdk
package entity 

import "github.com/milvus-io/milvus-sdk-go/internal/proto/schema"

// ColumnBool generated columns type for Bool
type ColumnBool struct {
	name   string
	values []bool
}

// Name returns column name
func (c *ColumnBool) Name() string {
	return c.name
}

// Type returns column FieldType
func (c *ColumnBool) Type() FieldType {
	return FieldTypeBool
}

// Len returns column values length
func (c *ColumnBool) Len() int {
	return len(c.values)
}

// FieldData return column data mapped to schema.FieldData
func (c *ColumnBool) FieldData() *schema.FieldData {
	fd := &schema.FieldData{
		Type: schema.DataType_Bool,
		FieldName: c.name,
	}
	fd.Field = &schema.FieldData_Scalars{
		Scalars: &schema.ScalarField{
			Data: &schema.ScalarField_IntData{
				IntData: &schema.IntArray{
					Data: []int32{},
				},
			},
		},
	}
	return fd
}

// NewColumnBool auto generated constructor
func NewColumnBool(name string, values []bool) *ColumnBool {
	return &ColumnBool {
		name: name,
		values: values,
	}
}
