// Code generated by go generate; DO NOT EDIT
// This file is generated by go generate at 2021-07-19 17:30:04.100488399 +0800 CST m=+0.005484811

package entity

import (
	"errors"
	"fmt"
)


var _ SearchParam = &IndexFlatSearchParam{}

// IndexFlatSearchParam search param struct for index type FLAT
type IndexFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexFlatSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexFlatSearchParam create index search param
func NewIndexFlatSearchParam(
	nprobe int,
) (*IndexFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexBinFlatSearchParam{}

// IndexBinFlatSearchParam search param struct for index type BIN_FLAT
type IndexBinFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexBinFlatSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexBinFlatSearchParam create index search param
func NewIndexBinFlatSearchParam(
	nprobe int,
) (*IndexBinFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexBinFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfFlatSearchParam{}

// IndexIvfFlatSearchParam search param struct for index type IVF_FLAT
type IndexIvfFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfFlatSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexIvfFlatSearchParam create index search param
func NewIndexIvfFlatSearchParam(
	nprobe int,
) (*IndexIvfFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexBinIvfFlatSearchParam{}

// IndexBinIvfFlatSearchParam search param struct for index type BIN_IVF_FLAT
type IndexBinIvfFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexBinIvfFlatSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexBinIvfFlatSearchParam create index search param
func NewIndexBinIvfFlatSearchParam(
	nprobe int,
) (*IndexBinIvfFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexBinIvfFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfSQ8SearchParam{}

// IndexIvfSQ8SearchParam search param struct for index type IVF_SQ8
type IndexIvfSQ8SearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfSQ8SearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexIvfSQ8SearchParam create index search param
func NewIndexIvfSQ8SearchParam(
	nprobe int,
) (*IndexIvfSQ8SearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfSQ8SearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfSQ8HSearchParam{}

// IndexIvfSQ8HSearchParam search param struct for index type IVF_SQ8_HYBRID
type IndexIvfSQ8HSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfSQ8HSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexIvfSQ8HSearchParam create index search param
func NewIndexIvfSQ8HSearchParam(
	nprobe int,
) (*IndexIvfSQ8HSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfSQ8HSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfPQSearchParam{}

// IndexIvfPQSearchParam search param struct for index type IVF_PQ
type IndexIvfPQSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfPQSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
	}
}

// NewIndexIvfPQSearchParam create index search param
func NewIndexIvfPQSearchParam(
	nprobe int,
) (*IndexIvfPQSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfPQSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexRNSGSearchParam{}

// IndexRNSGSearchParam search param struct for index type NSG
type IndexRNSGSearchParam struct { //auto generated fields
	search_length int
}

// Params returns index construction params, implementing Index interface
func(i *IndexRNSGSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"search_length": fmt.Sprintf("%v",i.search_length),
	}
}

// NewIndexRNSGSearchParam create index search param
func NewIndexRNSGSearchParam(
	search_length int,
) (*IndexRNSGSearchParam, error) {
	// auto generate parameters validation code, if any
	if search_length < 10 {
		return nil, errors.New("search_length not valid")
	}
	if search_length > 300 {
		return nil, errors.New("search_length not valid")
	}
	
	return &IndexRNSGSearchParam{ 
	//auto generated setting
	search_length: search_length,
	}, nil
}

var _ SearchParam = &IndexHNSWSearchParam{}

// IndexHNSWSearchParam search param struct for index type HNSW
type IndexHNSWSearchParam struct { //auto generated fields
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexHNSWSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"ef": fmt.Sprintf("%v",i.ef),
	}
}

// NewIndexHNSWSearchParam create index search param
func NewIndexHNSWSearchParam(
	ef int,
) (*IndexHNSWSearchParam, error) {
	// auto generate parameters validation code, if any
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexHNSWSearchParam{ 
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexRHNSWFlatSearchParam{}

// IndexRHNSWFlatSearchParam search param struct for index type RHNSW_FLAT
type IndexRHNSWFlatSearchParam struct { //auto generated fields
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexRHNSWFlatSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"ef": fmt.Sprintf("%v",i.ef),
	}
}

// NewIndexRHNSWFlatSearchParam create index search param
func NewIndexRHNSWFlatSearchParam(
	ef int,
) (*IndexRHNSWFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexRHNSWFlatSearchParam{ 
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexRHNSW_PQSearchParam{}

// IndexRHNSW_PQSearchParam search param struct for index type RHNSW_PQ
type IndexRHNSW_PQSearchParam struct { //auto generated fields
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexRHNSW_PQSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"ef": fmt.Sprintf("%v",i.ef),
	}
}

// NewIndexRHNSW_PQSearchParam create index search param
func NewIndexRHNSW_PQSearchParam(
	ef int,
) (*IndexRHNSW_PQSearchParam, error) {
	// auto generate parameters validation code, if any
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexRHNSW_PQSearchParam{ 
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexRHNSW_SQSearchParam{}

// IndexRHNSW_SQSearchParam search param struct for index type RHNSW_SQ
type IndexRHNSW_SQSearchParam struct { //auto generated fields
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexRHNSW_SQSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"ef": fmt.Sprintf("%v",i.ef),
	}
}

// NewIndexRHNSW_SQSearchParam create index search param
func NewIndexRHNSW_SQSearchParam(
	ef int,
) (*IndexRHNSW_SQSearchParam, error) {
	// auto generate parameters validation code, if any
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexRHNSW_SQSearchParam{ 
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexIvfHNSWSearchParam{}

// IndexIvfHNSWSearchParam search param struct for index type IVF_HNSW
type IndexIvfHNSWSearchParam struct { //auto generated fields
	nprobe int
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfHNSWSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"nprobe": fmt.Sprintf("%v",i.nprobe),
		"ef": fmt.Sprintf("%v",i.ef),
	}
}

// NewIndexIvfHNSWSearchParam create index search param
func NewIndexIvfHNSWSearchParam(
	nprobe int,

	ef int,
) (*IndexIvfHNSWSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexIvfHNSWSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexANNOYSearchParam{}

// IndexANNOYSearchParam search param struct for index type ANNOY
type IndexANNOYSearchParam struct { //auto generated fields
	search_k int
}

// Params returns index construction params, implementing Index interface
func(i *IndexANNOYSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"search_k": fmt.Sprintf("%v",i.search_k),
	}
}

// NewIndexANNOYSearchParam create index search param
func NewIndexANNOYSearchParam(
	search_k int,
) (*IndexANNOYSearchParam, error) {
	// auto generate parameters validation code, if any
	
	
	return &IndexANNOYSearchParam{ 
	//auto generated setting
	search_k: search_k,
	}, nil
}

var _ SearchParam = &IndexNGTPANNGSearchParam{}

// IndexNGTPANNGSearchParam search param struct for index type NGT_PANNG
type IndexNGTPANNGSearchParam struct { //auto generated fields
	max_search_edges int
	epsilon float64
}

// Params returns index construction params, implementing Index interface
func(i *IndexNGTPANNGSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"max_search_edges": fmt.Sprintf("%v",i.max_search_edges),
		"epsilon": fmt.Sprintf("%v",i.epsilon),
	}
}

// NewIndexNGTPANNGSearchParam create index search param
func NewIndexNGTPANNGSearchParam(
	max_search_edges int,

	epsilon float64,
) (*IndexNGTPANNGSearchParam, error) {
	// auto generate parameters validation code, if any
	if max_search_edges < -1 {
		return nil, errors.New("max_search_edges not valid")
	}
	if max_search_edges > 200 {
		return nil, errors.New("max_search_edges not valid")
	}
	
	if epsilon < -1.0 {
		return nil, errors.New("epsilon not valid")
	}
	if epsilon > 1.0 {
		return nil, errors.New("epsilon not valid")
	}
	
	return &IndexNGTPANNGSearchParam{ 
	//auto generated setting
	max_search_edges: max_search_edges,
	//auto generated setting
	epsilon: epsilon,
	}, nil
}

var _ SearchParam = &IndexNGTONNGSearchParam{}

// IndexNGTONNGSearchParam search param struct for index type NGT_ONNG
type IndexNGTONNGSearchParam struct { //auto generated fields
	max_search_edges int
	epsilon float64
}

// Params returns index construction params, implementing Index interface
func(i *IndexNGTONNGSearchParam) Params() map[string]string {
	return map[string]string {//auto generated mapping 
		"max_search_edges": fmt.Sprintf("%v",i.max_search_edges),
		"epsilon": fmt.Sprintf("%v",i.epsilon),
	}
}

// NewIndexNGTONNGSearchParam create index search param
func NewIndexNGTONNGSearchParam(
	max_search_edges int,

	epsilon float64,
) (*IndexNGTONNGSearchParam, error) {
	// auto generate parameters validation code, if any
	if max_search_edges < -1 {
		return nil, errors.New("max_search_edges not valid")
	}
	if max_search_edges > 200 {
		return nil, errors.New("max_search_edges not valid")
	}
	
	if epsilon < -1.0 {
		return nil, errors.New("epsilon not valid")
	}
	if epsilon > 1.0 {
		return nil, errors.New("epsilon not valid")
	}
	
	return &IndexNGTONNGSearchParam{ 
	//auto generated setting
	max_search_edges: max_search_edges,
	//auto generated setting
	epsilon: epsilon,
	}, nil
}

