// Code generated by go generate; DO NOT EDIT
// This file is generated by go generate at 2022-11-23 18:16:28.725402023 +0800 CST m=+0.004536238

package entity

import (
	"errors"
)


var _ SearchParam = &IndexFlatSearchParam{}

// IndexFlatSearchParam search param struct for index type FLAT
type IndexFlatSearchParam struct { //auto generated fields
}

// Params returns index construction params, implementing Index interface
func(i *IndexFlatSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
	}
}

// NewIndexFlatSearchParam create index search param
func NewIndexFlatSearchParam() (*IndexFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	return &IndexFlatSearchParam{ 
	}, nil
}

var _ SearchParam = &IndexBinFlatSearchParam{}

// IndexBinFlatSearchParam search param struct for index type BIN_FLAT
type IndexBinFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexBinFlatSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
	}
}

// NewIndexBinFlatSearchParam create index search param
func NewIndexBinFlatSearchParam(
	nprobe int,
) (*IndexBinFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexBinFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfFlatSearchParam{}

// IndexIvfFlatSearchParam search param struct for index type IVF_FLAT
type IndexIvfFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfFlatSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
	}
}

// NewIndexIvfFlatSearchParam create index search param
func NewIndexIvfFlatSearchParam(
	nprobe int,
) (*IndexIvfFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexBinIvfFlatSearchParam{}

// IndexBinIvfFlatSearchParam search param struct for index type BIN_IVF_FLAT
type IndexBinIvfFlatSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexBinIvfFlatSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
	}
}

// NewIndexBinIvfFlatSearchParam create index search param
func NewIndexBinIvfFlatSearchParam(
	nprobe int,
) (*IndexBinIvfFlatSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexBinIvfFlatSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfSQ8SearchParam{}

// IndexIvfSQ8SearchParam search param struct for index type IVF_SQ8
type IndexIvfSQ8SearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfSQ8SearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
	}
}

// NewIndexIvfSQ8SearchParam create index search param
func NewIndexIvfSQ8SearchParam(
	nprobe int,
) (*IndexIvfSQ8SearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfSQ8SearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexIvfPQSearchParam{}

// IndexIvfPQSearchParam search param struct for index type IVF_PQ
type IndexIvfPQSearchParam struct { //auto generated fields
	nprobe int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfPQSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
	}
}

// NewIndexIvfPQSearchParam create index search param
func NewIndexIvfPQSearchParam(
	nprobe int,
) (*IndexIvfPQSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	return &IndexIvfPQSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	}, nil
}

var _ SearchParam = &IndexHNSWSearchParam{}

// IndexHNSWSearchParam search param struct for index type HNSW
type IndexHNSWSearchParam struct { //auto generated fields
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexHNSWSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"ef": i.ef,
	}
}

// NewIndexHNSWSearchParam create index search param
func NewIndexHNSWSearchParam(
	ef int,
) (*IndexHNSWSearchParam, error) {
	// auto generate parameters validation code, if any
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexHNSWSearchParam{ 
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexIvfHNSWSearchParam{}

// IndexIvfHNSWSearchParam search param struct for index type IVF_HNSW
type IndexIvfHNSWSearchParam struct { //auto generated fields
	nprobe int
	ef int
}

// Params returns index construction params, implementing Index interface
func(i *IndexIvfHNSWSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"nprobe": i.nprobe,
		"ef": i.ef,
	}
}

// NewIndexIvfHNSWSearchParam create index search param
func NewIndexIvfHNSWSearchParam(
	nprobe int,

	ef int,
) (*IndexIvfHNSWSearchParam, error) {
	// auto generate parameters validation code, if any
	if nprobe < 1 {
		return nil, errors.New("nprobe not valid")
	}
	if nprobe > 65536 {
		return nil, errors.New("nprobe not valid")
	}
	
	if ef < 1 {
		return nil, errors.New("ef not valid")
	}
	if ef > 32768 {
		return nil, errors.New("ef not valid")
	}
	
	return &IndexIvfHNSWSearchParam{ 
	//auto generated setting
	nprobe: nprobe,
	//auto generated setting
	ef: ef,
	}, nil
}

var _ SearchParam = &IndexANNOYSearchParam{}

// IndexANNOYSearchParam search param struct for index type ANNOY
type IndexANNOYSearchParam struct { //auto generated fields
	search_k int
}

// Params returns index construction params, implementing Index interface
func(i *IndexANNOYSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"search_k": i.search_k,
	}
}

// NewIndexANNOYSearchParam create index search param
func NewIndexANNOYSearchParam(
	search_k int,
) (*IndexANNOYSearchParam, error) {
	// auto generate parameters validation code, if any
	
	
	return &IndexANNOYSearchParam{ 
	//auto generated setting
	search_k: search_k,
	}, nil
}

var _ SearchParam = &IndexDISKANNSearchParam{}

// IndexDISKANNSearchParam search param struct for index type DISKANN
type IndexDISKANNSearchParam struct { //auto generated fields
	search_list int
}

// Params returns index construction params, implementing Index interface
func(i *IndexDISKANNSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"search_list": i.search_list,
	}
}

// NewIndexDISKANNSearchParam create index search param
func NewIndexDISKANNSearchParam(
	search_list int,
) (*IndexDISKANNSearchParam, error) {
	// auto generate parameters validation code, if any
	if search_list < 1 {
		return nil, errors.New("search_list not valid")
	}
	if search_list > 65535 {
		return nil, errors.New("search_list not valid")
	}
	
	return &IndexDISKANNSearchParam{ 
	//auto generated setting
	search_list: search_list,
	}, nil
}

var _ SearchParam = &IndexAUTOINDEXSearchParam{}

// IndexAUTOINDEXSearchParam search param struct for index type AUTOINDEX
type IndexAUTOINDEXSearchParam struct { //auto generated fields
	level int
}

// Params returns index construction params, implementing Index interface
func(i *IndexAUTOINDEXSearchParam) Params() map[string]interface{} {
	return map[string]interface{} {//auto generated mapping 
		"level": i.level,
	}
}

// NewIndexAUTOINDEXSearchParam create index search param
func NewIndexAUTOINDEXSearchParam(
	level int,
) (*IndexAUTOINDEXSearchParam, error) {
	// auto generate parameters validation code, if any
	if level < 1 {
		return nil, errors.New("level not valid")
	}
	if level > 3 {
		return nil, errors.New("level not valid")
	}
	
	return &IndexAUTOINDEXSearchParam{ 
	//auto generated setting
	level: level,
	}, nil
}

