apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: ${RELEASE_NAME}
spec:
  mode: cluster
  dependencies:
    etcd:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          resources:
            requests:
              memory: 256Mi
    pulsar:
      inCluster:
        deletionPolicy: Delete
        pvcDeletion: true
        values:
          components:
            autorecovery: false
            functions: false
            toolset: false
            pulsar_manager: false
          monitoring:
            prometheus: false
            grafana: false
            node_exporter: false
            alert_manager: false
          proxy:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.1
                memory: 256Mi
            wsResources:
              requests:
                memory: 256Mi
                cpu: 0.1
          configData:
            PULSAR_MEM: >
              -Xms256m -Xmx256m
            PULSAR_GC: >
              -XX:MaxDirectMemorySize=512m
            httpNumThreads: "50"
          bookkeeper:
            replicaCount: 2
            resources:
              requests:
                cpu: 0.1
                memory: 512Mi
            configData:
              PULSAR_MEM: >
                -Xms512m
                -Xmx512m
                -XX:MaxDirectMemorySize=1024m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+UseG1GC -XX:MaxGCPauseMillis=10
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
                -XX:+PerfDisableSharedMem
                -XX:+PrintGCDetails
          zookeeper:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.1
                memory: 256Mi
            configData:
              PULSAR_MEM: >
                -Xms512m
                -Xmx512m
              PULSAR_GC: >
                -Dcom.sun.management.jmxremote
                -Djute.maxbuffer=10485760
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:+DisableExplicitGC
                -XX:+PerfDisableSharedMem
                -Dzookeeper.forceSync=no
          broker:
            replicaCount: 1
            resources:
              requests:
                cpu: 0.1
                memory: 512Mi
            configData:
              PULSAR_MEM: >
                -Xms512m
                -Xmx512m
                -XX:MaxDirectMemorySize=1024m
              PULSAR_GC: >
                -Dio.netty.leakDetectionLevel=disabled
                -Dio.netty.recycler.linkCapacity=1024
                -XX:+ParallelRefProcEnabled
                -XX:+UnlockExperimentalVMOptions
                -XX:+DoEscapeAnalysis
                -XX:ParallelGCThreads=32
                -XX:ConcGCThreads=32
                -XX:G1NewSizePercent=50
                -XX:+DisableExplicitGC
                -XX:-ResizePLAB
                -XX:+ExitOnOutOfMemoryError
  components:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    queryNode:
      replicas: 4
    dataNode:
      replicas: 1
    indexNode:
      replicas: 1
  config:
    log:
      level: debug